spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kim
    password: 8531
    url: jdbc:mysql://localhost:3306/RestApi1?serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
